<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="apple-itunes-app" content="app-id=600033550, affiliate-data=myAffiliateData, app-argument=myURL">
    <title>Patter - A chat client for app.net</title>

    <link rel="shortcut icon" href="favicon.ico"/>
    <link rel="stylesheet" style="text/css"
          href="/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" style="text/css"
          href="/css/bootstrap/bootstrap-responsive.min.css">

    {% block javascript %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>
